
name: Deploy AWS Lambda # name of our workflow

on: # defines when workflow should be run
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs: # defines jobs to run in workflow
  deploy-lambda: # name of our job
    runs-on: ubuntu-latest # sets or specifies the runner
    steps:
      - uses: actions/checkout@v2 # sets up python environment

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies # installs any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Credentials # sets up our aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Lambda Function to AWS # zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
      